MC_CLIENT_ID:
MC_CLIENT_SECRET:
logging:
  level:
    root: info
security:

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:baeldung.p12
    key-store-password: changeit
    key-alias: baeldung
  port: 8443
spring:
  security:
    oauth2:
      client:
        registration:
          social:
            clientAuthenticationMethod: POST
            client-id: ${MC_CLIENT_ID}
            client-secret: ${MC_CLIENT_SECRET}
            client-name: Salesforce user
            redirect-uri: https://127.0.0.1:8443/login/oauth2/code/social
            authorization-grant-type: authorization_code
        provider:
          social:
            authorization-uri: https://mc882zkqmv0jpg-dz8-ng69z7ws4.auth-qa1.marketingcloudqaapis.com/v2/authorize
            token-uri: https://mc882zkqmv0jpg-dz8-ng69z7ws4.auth-qa1.marketingcloudqaapis.com/v2/token
#            user-info-uri: https://mc882zkqmv0jpg-dz8-ng69z7ws4.auth-qa1.marketingcloudqaapis.com/v2/userinfo
#            jwkSetUri: https://login.marketingcloud.com/id/keys
            user-name-attribute: iss
  session:
    store-type: redis
  redis:
    url: ${REDIS_URL}