SALSFORCE_CLIENT_ID: 3MVG9ZF4bs_.MKujBFvgmaCZKP9THCjqOYr9u1f.kxo3stRAdvqdRfCEiyzu0rVNpBR7x2G7LjwJlZABIFRNr
SALSFORCE_CLIENT_SECRET: 3419DC4A900AFAD0AD9B5D790C763AD43F9E64677872FCA9D9060C11C4DD938E
spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            client-id: ${SALSFORCE_CLIENT_ID}
            client-secret: ${SALSFORCE_CLIENT_SECRET}
            client-name: Salesforce user
            redirect-uri: https://spring-salesforce-oauth2.herokuapp.com/login/oauth2/code/salesforce
            authorization-grant-type: authorization_code
        provider:
          salesforce:
            authorization-uri: https://login.salesforce.com/services/oauth2/authorize
            token-uri: https://login.salesforce.com/services/oauth2/token
            user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
            user-name-attribute: preferred_username
  session:
    store-type: redis
  redis:
    url: ${REDIS_URL}
#logging:
#  level:
#    root: debug